name: CI
on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    name: Test
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Navi
        run: curl -sSL https://navi-lang.org/install | sh
      - name: Test
        run: navi test .
